global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scheduler-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:9090']
    metrics_path: '/metrics'

  - job_name: 'scheduler-worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['worker:9090']
    metrics_path: '/metrics'